In [42]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [43]:
file_path= "/content/drive/MyDrive/Instacart/Instacart.zip"
import zipfile
with zipfile.ZipFile(file_path, 'r') as zip_ref:
  zip_ref.extractall("/content/drive/MyDrive/Instacart/extracted_folder")

In [44]:
!ls "/content/drive/MyDrive/Instacart/extracted_folder"

aisles.csv	 order_products__prior.csv  orders.csv
departments.csv  order_products__train.csv  products.csv

In [45]:
import pandas as pd
aisles = pd.read_csv("/content/drive/MyDrive/Instacart/extracted_folder/aisles.csv")
products = pd.read_csv("/content/drive/MyDrive/Instacart/extracted_folder/products.csv")
order_products__prior = pd.read_csv("/content/drive/MyDrive/Instacart/extracted_folder/order_products__prior.csv")
departments = pd.read_csv("/content/drive/MyDrive/Instacart/extracted_folder/departments.csv")
order_products__train = pd.read_csv("/content/drive/MyDrive/Instacart/extracted_folder/order_products__train.csv")

In [46]:
products.head()

,product_id,product_name,aisle_id,department_id
0,1,Chocolate Sandwich Cookies,61,19
1,2,All-Seasons Salt,104,13
2,3,Robust Golden Unsweetened Oolong Tea,94,7
3,4,Smart Ones Classic Favorites Mini Rigatoni Wit...,38,1
4,5,Green Chile Anytime Sauce,5,13

In [47]:
orders = pd.read_csv("/content/drive/MyDrive/Instacart/extracted_folder/orders.csv")

In [48]:
orders.head()

,order_id,user_id,eval_set,order_number,order_dow,order_hour_of_day,days_since_prior_order
0,2539329,1,prior,1,2,8,NaN
1,2398795,1,prior,2,3,7,15.0
2,473747,1,prior,3,3,12,21.0
3,2254736,1,prior,4,4,7,29.0
4,431534,1,prior,5,4,15,28.0

In [49]:
orders.isnull().sum()

order_id                       0
user_id                        0
eval_set                       0
order_number                   0
order_dow                      0
order_hour_of_day              0
days_since_prior_order    206209
dtype: int64

In [50]:
products.isnull().sum()

product_id       0
product_name     0
aisle_id         0
department_id    0
dtype: int64

In [51]:
order_products__prior.isnull().sum()

order_id             0
product_id           0
add_to_cart_order    0
reordered            0
dtype: int64

In [52]:
order_products__train.isnull().sum()

order_id             0
product_id           0
add_to_cart_order    0
reordered            0
dtype: int64

In [53]:
aisles.isnull().sum()

aisle_id    0
aisle       0
dtype: int64

In [54]:
departments.isnull().sum()

department_id    0
department       0
dtype: int64

In [55]:
orders.dtypes

order_id                    int64
user_id                     int64
eval_set                   object
order_number                int64
order_dow                   int64
order_hour_of_day           int64
days_since_prior_order    float64
dtype: object

In [56]:
orders.dropna(subset = ['days_since_prior_order'],inplace = True)

In [57]:
orders.isnull().sum()

order_id                  0
user_id                   0
eval_set                  0
order_number              0
order_dow                 0
order_hour_of_day         0
days_since_prior_order    0
dtype: int64

In [58]:
orders.dtypes

order_id                    int64
user_id                     int64
eval_set                   object
order_number                int64
order_dow                   int64
order_hour_of_day           int64
days_since_prior_order    float64
dtype: object

In [59]:
orders.head()

,order_id,user_id,eval_set,order_number,order_dow,order_hour_of_day,days_since_prior_order
1,2398795,1,prior,2,3,7,15.0
2,473747,1,prior,3,3,12,21.0
3,2254736,1,prior,4,4,7,29.0
4,431534,1,prior,5,4,15,28.0
5,3367565,1,prior,6,2,7,19.0

In [61]:
orders = pd.read_csv("/content/drive/MyDrive/Instacart/extracted_folder/orders.csv")

In [62]:
orders.head()

,order_id,user_id,eval_set,order_number,order_dow,order_hour_of_day,days_since_prior_order
0,2539329,1,prior,1,2,8,NaN
1,2398795,1,prior,2,3,7,15.0
2,473747,1,prior,3,3,12,21.0
3,2254736,1,prior,4,4,7,29.0
4,431534,1,prior,5,4,15,28.0

In [63]:
orders['eval_set'].unique()

array(['prior', 'train', 'test'], dtype=object)

In [64]:
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()
orders['eval_set_encoded'] = le.fit_transform(orders['eval_set'])

In [65]:
orders.dtypes

order_id                    int64
user_id                     int64
eval_set                   object
order_number                int64
order_dow                   int64
order_hour_of_day           int64
days_since_prior_order    float64
eval_set_encoded            int64
dtype: object

In [66]:
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()

orders['eval_set_encoded'] = le.fit_transform(orders['eval_set'])

print("Classes found by LabelEncoder:", le.classes_)
print("Encoded 'eval_set' values:\n", orders[['eval_set', 'eval_set_encoded']].head())

Classes found by LabelEncoder: ['prior' 'test' 'train']
Encoded 'eval_set' values:
   eval_set  eval_set_encoded
0    prior                 0
1    prior                 0
2    prior                 0
3    prior                 0
4    prior                 0

In [67]:
orders.dtypes

order_id                    int64
user_id                     int64
eval_set                   object
order_number                int64
order_dow                   int64
order_hour_of_day           int64
days_since_prior_order    float64
eval_set_encoded            int64
dtype: object

In [68]:
orders['eval_set'] = le.fit_transform(orders['eval_set'])

In [69]:
orders.dtypes

order_id                    int64
user_id                     int64
eval_set                    int64
order_number                int64
order_dow                   int64
order_hour_of_day           int64
days_since_prior_order    float64
eval_set_encoded            int64
dtype: object

In [71]:
orders.isnull().sum()

order_id                       0
user_id                        0
eval_set                       0
order_number                   0
order_dow                      0
order_hour_of_day              0
days_since_prior_order    206209
eval_set_encoded               0
dtype: int64

In [72]:
orders.dropna(subset = ['days_since_prior_order'],inplace = True)

In [73]:
orders.isnull().sum()

order_id                  0
user_id                   0
eval_set                  0
order_number              0
order_dow                 0
order_hour_of_day         0
days_since_prior_order    0
eval_set_encoded          0
dtype: int64

In [74]:
orders.dtypes

order_id                    int64
user_id                     int64
eval_set                    int64
order_number                int64
order_dow                   int64
order_hour_of_day           int64
days_since_prior_order    float64
eval_set_encoded            int64
dtype: object

In [75]:
orders['days_since_prior_order']= orders['days_since_prior_order'].astype('int')

In [76]:
orders.dtypes

order_id                  int64
user_id                   int64
eval_set                  int64
order_number              int64
order_dow                 int64
order_hour_of_day         int64
days_since_prior_order    int64
eval_set_encoded          int64
dtype: object

In [77]:
orders.head()

,order_id,user_id,eval_set,order_number,order_dow,order_hour_of_day,days_since_prior_order,eval_set_encoded
1,2398795,1,0,2,3,7,15,0
2,473747,1,0,3,3,12,21,0
3,2254736,1,0,4,4,7,29,0
4,431534,1,0,5,4,15,28,0
5,3367565,1,0,6,2,7,19,0

In [78]:
products = pd.read_csv("/content/drive/MyDrive/Instacart/extracted_folder/products.csv")

In [79]:
products.head()

,product_id,product_name,aisle_id,department_id
0,1,Chocolate Sandwich Cookies,61,19
1,2,All-Seasons Salt,104,13
2,3,Robust Golden Unsweetened Oolong Tea,94,7
3,4,Smart Ones Classic Favorites Mini Rigatoni Wit...,38,1
4,5,Green Chile Anytime Sauce,5,13

In [80]:
products.isnull().sum()

product_id       0
product_name     0
aisle_id         0
department_id    0
dtype: int64

In [81]:
products.dtypes

product_id        int64
product_name     object
aisle_id          int64
department_id     int64
dtype: object

In [82]:
import pandas as pd

aisle_id = pd.read_csv ("/content/drive/MyDrive/Instacart/extracted_folder/aisles.csv")

In [83]:
!ls "/content/drive/MyDrive/Instacart/extracted_folder/"

aisles.csv	 order_products__prior.csv  orders.csv
departments.csv  order_products__train.csv  products.csv

In [84]:
aisle_id.isnull().sum()

aisle_id    0
aisle       0
dtype: int64

In [85]:
aisle_id.dtypes

aisle_id     int64
aisle       object
dtype: object

In [86]:
departments = pd.read_csv("/content/drive/MyDrive/Instacart/extracted_folder/departments.csv")

In [87]:
departments.isnull().sum()

department_id    0
department       0
dtype: int64

In [88]:
departments.dtypes

department_id     int64
department       object
dtype: object

In [89]:
order_products__prior = pd.read_csv("/content/drive/MyDrive/Instacart/extracted_folder/order_products__prior.csv")

In [90]:
order_products__prior.isnull().sum()

order_id             0
product_id           0
add_to_cart_order    0
reordered            0
dtype: int64

In [91]:
order_products__prior.dtypes

order_id             int64
product_id           int64
add_to_cart_order    int64
reordered            int64
dtype: object

In [92]:
order_products__train = pd.read_csv("/content/drive/MyDrive/Instacart/extracted_folder/order_products__train.csv")

In [93]:
order_products__train.isnull().sum()

order_id             0
product_id           0
add_to_cart_order    0
reordered            0
dtype: int64

In [94]:
order_products__train.dtypes

order_id             int64
product_id           int64
add_to_cart_order    int64
reordered            int64
dtype: object

In [95]:
duplicates = order_products__train.duplicated

In [96]:
order_products__train[duplicates]

Empty DataFrame
Columns: [order_id, product_id, add_to_cart_order, reordered]
Index: []

In [97]:
duplicates = order_products__prior.duplicated(keep=False)
duplicate_rows = order_products__prior[duplicates]
print(duplicate_rows)

Empty DataFrame
Columns: [order_id, product_id, add_to_cart_order, reordered]
Index: []

In [98]:
duplicates = orders.duplicated(keep=False)
duplicate_rows = orders[duplicates]
print(duplicate_rows)

Empty DataFrame
Columns: [order_id, user_id, eval_set, order_number, order_dow, order_hour_of_day, days_since_prior_order, eval_set_encoded]
Index: []

In [99]:
products = pd.read_csv("/content/drive/MyDrive/Instacart/extracted_folder/products.csv")
duplicates = products.duplicated(keep=False)
duplicate_rows = products[duplicates]
print(duplicate_rows)

Empty DataFrame
Columns: [product_id, product_name, aisle_id, department_id]
Index: []

In [100]:
duplicates = departments.duplicated(keep=False)
duplicate_rows = departments[duplicates]
print(duplicate_rows)

Empty DataFrame
Columns: [department_id, department]
Index: []

In [101]:
duplicates = aisle_id.duplicated(keep=False)
duplicate_rows = aisle_id[duplicates]
print(duplicate_rows)

Empty DataFrame
Columns: [aisle_id, aisle]
Index: []

In [102]:
duplicates = order_products__train.duplicated(keep=False)
duplicate_rows = order_products__train[duplicates]
print(duplicate_rows)

Empty DataFrame
Columns: [order_id, product_id, add_to_cart_order, reordered]
Index: []

In [103]:
duplicates = order_products__prior.duplicated(keep=False)
duplicate_rows = order_products__prior[duplicates]
print(duplicate_rows)

Empty DataFrame
Columns: [order_id, product_id, add_to_cart_order, reordered]
Index: []

In [104]:
prior_merged = pd.merge(order_products__prior, products, on='product_id', how='left')

In [105]:
prior_merged.head()

,order_id,product_id,add_to_cart_order,reordered,product_name,aisle_id,department_id
0,2,33120,1,1,Organic Egg Whites,86,16
1,2,28985,2,1,Michigan Organic Kale,83,4
2,2,9327,3,0,Garlic Powder,104,13
3,2,45918,4,1,Coconut Butter,19,13
4,2,30035,5,0,Natural Sweetener,17,13

In [106]:
prior_merged = prior_merged.merge(aisle_id, on='aisle_id', how='left')

In [107]:
prior_merged.head()

,order_id,product_id,add_to_cart_order,reordered,product_name,aisle_id,department_id,aisle
0,2,33120,1,1,Organic Egg Whites,86,16,eggs
1,2,28985,2,1,Michigan Organic Kale,83,4,fresh vegetables
2,2,9327,3,0,Garlic Powder,104,13,spices seasonings
3,2,45918,4,1,Coconut Butter,19,13,oils vinegars
4,2,30035,5,0,Natural Sweetener,17,13,baking ingredients

In [108]:
prior_merged = prior_merged.merge(departments, on='department_id', how='left')

In [109]:
prior_merged.head()

,order_id,product_id,add_to_cart_order,reordered,product_name,aisle_id,department_id,aisle,department
0,2,33120,1,1,Organic Egg Whites,86,16,eggs,dairy eggs
1,2,28985,2,1,Michigan Organic Kale,83,4,fresh vegetables,produce
2,2,9327,3,0,Garlic Powder,104,13,spices seasonings,pantry
3,2,45918,4,1,Coconut Butter,19,13,oils vinegars,pantry
4,2,30035,5,0,Natural Sweetener,17,13,baking ingredients,pantry

In [110]:
import pandas as pd

In [ ]:
full_data = pd.merge(prior_merged, orders, on='order_id', how='left')